### ISSUE TITLE
[s3-proxy] Re-create Pods when configuration is updated

### ISSUE THREAD

**Issue by MatthiasLohr** [oxyno-zeta/helm-charts#16]
Hi,

currently, when I just update the `configFiles` settings, the Pods are not recreated, so the changed configuration does not take place. I currently work around it with a custom manual annotation, but it would come handy if the Helm chart could take care of it. Thanks!

Best regards
Matthias

**Comment by oxyno-zeta** [comment]
Hello,

Thanks for your issue.

This haven't to be done because Kubernetes will update/change file created on the filesystem linked to the configmap after waiting a little bit. You can see the reload in the logs.

This have been described here [https://github.com/oxyno-zeta/s3-proxy/issues/119](https://github.com/oxyno-zeta/s3-proxy/issues/119).

I will close this as this isn't a bug or something that will be changed. This was the aim of doing a hot reload of the config in s3-proxy ;) .

Regads,

**Comment by MatthiasLohr** [comment]
Ok, then I was just too impatient. Thanks for the information!
